language: elixir
dist: trusty
elixir:
  - 1.6.3
otp_release:
  - 20.0

addons:
  postgresql: "9.6"

services:
  - redis-server

env:
  global:
    - MIX_ENV=test
    - PRONTO_PULL_REQUEST_ID=$TRAVIS_PULL_REQUEST
    - TRAVIS_NODE_VERSION="6.10.1"

cache:
  yarn: true
  directories: â€” /home/travis/.rvm/
    - travis_phantomjs
    - node_modules

before_install:
  - "export PHANTOMJS_VERSION=2.1.1"
  - "export PATH=$PWD/travis_phantomjs/phantomjs-$PHANTOMJS_VERSION-linux-x86_64/bin:$PATH"
  - "if [ ! -e $PWD/travis_phantomjs/phantomjs-$PHANTOMJS_VERSION-linux-x86_64/bin ]; then rm -rf $PWD/travis_phantomjs; mkdir -p $PWD/travis_phantomjs; fi"
  - "if [ ! -e $PWD/travis_phantomjs/phantomjs-$PHANTOMJS_VERSION-linux-x86_64/bin ]; then wget https://github.com/Medium/phantomjs/releases/download/v$PHANTOMJS_VERSION/phantomjs-$PHANTOMJS_VERSION-linux-x86_64.tar.bz2 -O $PWD/travis_phantomjs/phantomjs-$PHANTOMJS_VERSION-linux-x86_64.tar.bz2; fi"
  - "if [ ! -e $PWD/travis_phantomjs/phantomjs-$PHANTOMJS_VERSION-linux-x86_64/bin ]; then tar -xvf $PWD/travis_phantomjs/phantomjs-$PHANTOMJS_VERSION-linux-x86_64.tar.bz2 -C $PWD/travis_phantomjs; fi"
  - "phantomjs --version"
  - nvm install $TRAVIS_NODE_VERSION
  - npm install -g yarn

before_script:
  - rvm reload
  - rvm install ruby-2.3.1
  - gem install pronto-credo
  - yarn

script:
  - if [ $PULL_REQUEST_ID != false ]; then pronto run -f github_pr; fi
  - mix coveralls.travis
  - cd assets && yarn run gulp build
